[project]
name = "mcp-nlp"
version = "0.0.1"
description = "MCP-NLP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp==2.3.4",
    "loguru==0.7.3",
    "textdistance==4.6.2"
]
